ACCESS_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
REPOS:
  - ioos/compliance-checker
  - ioos/catalog
  - sci-wms/sci-wms
  - asascience-open/ncsos
  - nctoolbox/nctoolbox
  - ioos/ckanext-ioos-theme
  - ioos/compliance-checker-web
  - ioos/glider-dac
  - ioos/cc-plugin-glider
  - ioos/cc-plugin-ncei
  - ioos/gliders
  - ioos/ioos-us
  - ioos/catalog-harvesting
  - ioos/catalog-harvest-registry
  - ioos/pyoos
